name: Java Maven CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        run: |
          git clone https://github.com/keyko-io/nevermind-tools
          cd nevermind-tools
          sudo bash -x start_nevermind.sh --no-commons --no-faucet --no-dashboard --latest 2>&1 > start_nevermind.log &
          cd ..
          sleep 60
          /bin/bash src/test/resources/scripts/updateConfAddresses.sh
          mvn clean verify -P all-tests
